# Generated by Django 3.2.6 on 2021-09-01 07:34

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/default.jpg', upload_to=profiles.models.upload_to, verbose_name='Profile picture'),
        ),
    ]
