# Generated by Django 3.2.6 on 2021-08-31 06:14

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_picture', models.ImageField(default='pets/default.jpg', upload_to=app.models.upload_to, verbose_name='Pet picture')),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbits', 'Rabbits'), ('Hourses', 'Hourses'), ('Small and Fury Pets', 'Small and Fury Pets')], max_length=200, verbose_name='Species')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
