# Generated by Django 3.2.6 on 2021-08-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
        ),
    ]
