# Generated by Django 3.2.6 on 2021-08-31 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 44, 18, 910711), verbose_name='Posted date'),
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique_for_date='posted', verbose_name='Slug'),
        ),
    ]
