# Generated by Django 3.2.6 on 2021-09-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pet_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.species'),
        ),
    ]
